version: "3"
services:
  # Containers for local development external deps

  devstack_app_deps:
    image: tianon/true
    restart: "no"
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - metrics_pushgateway
      # TODO: remove
      - devstack_tools

  devstack_tools:
    image: tianon/true
    restart: "no"
    depends_on:
      - pgadmin

  postgres:
    container_name: postgres
    image: postgres:latest
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    env_file:
      - $PWD/devstack/.env
    volumes:
      - $PWD/devstack/postgres/data:/var/lib/postgresql/data/ # persist data even if container shuts down

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.15
    env_file:
      - $PWD/devstack/.env
    depends_on:
      - "postgres"
    ports:
      - 5050:5050
    volumes:
      - "$PWD/devstack/pgadmin/config/servers.json:/pgadmin4/servers.json"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    env_file:
      - $PWD/devstack/.env
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - $PWD/devstack/rabbitmq/data:/var/lib/rabbitmq
      - $PWD/devstack/rabbitmq/logs:/var/log/rabbitmq
      - $PWD/devstack/rabbitmq/etc:/etc/rabbitmq

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - $PWD/devstack/redis/data:/var/lib/redis
    #   - $PWD/devstack/redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - $PWD/devstack/.env

  metrics_pushgateway:
    container_name: metrics_pushgateway
    image: prom/pushgateway:latest
    ports:
      - 9091:9091
