name: PHP Composer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
        php-version:
          - '8.0'
        package:
          - reactphp
          - swoole
    name: "${{ matrix.package }} - PHP ${{ matrix.php-version }} ${{ matrix.operating-system }}"
    env:
      php-extensions: swoole
      matrix-key: ${{ matrix.package }}-${{ matrix.php-version }}-${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2

      # -- Docker tools
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-step1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # -- PHP tools

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.php-extensions }}
          key: ${{ env.php-extensions }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: ${{ env.php-extensions }}
          ini-values: memory_limit=4096M
          tools: composer:v2
          coverage: xdebug
        env:
          fail-fast: true

      # -- Acceptance tests
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: yarn --cwd acceptance-tests/ install --frozen-lockfile

      # -- App

      - name: Cache vendor/
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: projects/${{ matrix.package }}/vendor
          key: ${{ runner.os }}-${{ env.matrix-key }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.matrix-key }}-php-

      - name: Cache vendor-bin/tools/vendor/
        id: composer-bin-cache
        uses: actions/cache@v2
        with:
          path: projects/${{ matrix.package }}/vendor-bin/tools/vendor
          key: ${{ runner.os }}-${{ env.matrix-key }}-php-bin-${{ hashFiles('**/vendor-bin/**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.matrix-key }}-php-bin-

      - name: Validate composer.json and composer.lock
        run: composer --working-dir=projects/${{ matrix.package }} validate

      - name: Install Composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer --working-dir=projects/${{ matrix.package }} install --prefer-dist --no-progress --no-suggest

      - name: Verify
        run: composer --working-dir=projects/${{ matrix.package }} verify

      - name: Start devstack_app_deps
        run: docker-compose -f projects/${{ matrix.package }}/docker-compose.yaml -f docker-compose.yaml up --build -d devstack_app_deps

      - name: Run project unit and (whitebox) integration tests
        run: composer --working-dir=projects/${{ matrix.package }} test

      - name: Start devstack_app
        run: docker-compose -f projects/${{ matrix.package }}/docker-compose.yaml -f docker-compose.yaml up --build -d devstack_app

      - name: Run project acceptance tests
        run: yarn --cwd acceptance-tests/ test

      - name: Stop devstack
        if: ${{ always() }}
        run: docker-compose -f projects/${{ matrix.package }}/docker-compose.yaml -f docker-compose.yaml down

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.matrix-key }}-reports
          path: projects/${{ matrix.package }}/reports/

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.matrix-key }}-acceptance-test-reports
          path: acceptance-tests/reports/
